version:
  {
    minimum: 0.1.2-dev,
    maximum: 0.1.2-dev # this should NOT be made a variable, but should be tested after every tag is created
  }
model:
    {
      dimension: 3, # the dimension of the model and dataset: defines dimensionality of computations
      base_filters: "adsa"
    }